name: CynagenLevels
version: '${project.version}'
main: me.kyrobi.cynagenlevels.CynagenLevels
api-version: '1.20'
depend:
  - DiscordSRV
softdepend:
  - McMMO
commands:
  addplayer:
    description: Add player to the system
  level:
    description: Get your level
  leveltop:
    description: Get the level leaderboard
