name: CynagenLevels
version: '1.0-SNAPSHOT'
main: me.kyrobi.cynagenlevels.CynagenLevels
api-version: '1.20'
depend:
  - DiscordSRV
commands:
  addplayer:
    description: Add player to the system
  level:
    description: Get your level
